### ISSUE TITLE
[translation]: Need help with translations to French

### ISSUE THREAD

**Issue by maccyber** [Alheimsins/b5-result-text#19]
We need help with result text translations to French, see [example page](https://bigfive-test.com/result/58a70606a835c400c8b38e84) 

The questions is [already translated](https://bigfive-test.com/test/fr)

If you want to help by translating the results to another language this is how you do it.
* clone the repo
* find a language you know in lib/data
* duplicate the folder and rename it to the language you will translate
* use ISO 639-1 language code as folder name.
* translate the content of all files except index.js
* don't change filenames or properties
* add your language code to the languages.json file
* submit pull request
* happiness :-)

It's a lot of text, so if you just translate some parts, push it anyways and hopefully someone can pick up the rest

**Comment by CCoupris** [comment]
Hey I would help you to translate your content ! (I'm french and I speak english but I'm a new member of GitHub, so you list will help me !)

**Comment by maccyber** [comment]
Awesome. Welcome to github @CCoupris :smile: 
Just ask if you need some help getting started.

No questions is stupid over here!

**Comment by CCoupris** [comment]
Okay thanks ! 
I've just finish to translate one part (agreeableness.js) but I don't know how to put it here :(

**Comment by CCoupris** [comment]
I have a problem, I can't upload anything.

![Uploading screen github.png…]()

Can you create a new folder for the french part, please ?

**Comment by kant1** [comment]
Hy

I can help for it.
I check CCoupris account and nothing was push.
I restart from scratch the translation.

**Comment by zrrrzzt** [comment]
@kant1 awsm ❤️

**Comment by kant1** [comment]
simultaneously, I send an email to contact of https://bigfive-test.com/ for en translate issue in FR questions label.
The question 41 is a duplication of the 42. I will do a PR for this issue. Could you give me the concerned repo plz ?

**Comment by zrrrzzt** [comment]
https://github.com/Alheimsins/b5-johnson-120-ipip-neo-pi-r

**Comment by kant1** [comment]
Translation finished.
Before send the PR I will review it with my wife who's psy.
It will be more accurate I think.

**Comment by kant1** [comment]
PR send.

**Comment by zrrrzzt** [comment]
Merged and released

thx @kant1
